# Generated by Django 4.1.13 on 2024-02-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_orderdeliveryaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdeliveryaddress',
            name='phone',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderdeliveryaddress',
            name='country',
            field=models.CharField(default='Ireland', max_length=100),
        ),
    ]
