# Generated by Django 4.1.13 on 2024-02-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_orderdeliveryaddress_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdeliveryaddress',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
