# Generated by Django 4.1.13 on 2024-02-22 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_basket_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='document',
            field=models.CharField(default='0000000000', max_length=20),
        ),
    ]
