# Generated by Django 4.1.13 on 2024-02-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_order_created_at_order_currency_order_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='customer_id',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
