# Generated by Django 4.1.13 on 2024-02-28 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_remove_order_customer_id_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stripe_session_id',
            new_name='stripe_id',
        ),
    ]
