# Generated by Django 4.1.13 on 2024-02-28 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_rename_stripe_session_id_order_stripe_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_address',
            new_name='address',
        ),
    ]
