# Generated by Django 4.1.13 on 2024-02-28 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_rename_address_order_oda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stripe_id',
            new_name='sid',
        ),
    ]
