# Generated by Django 4.1.13 on 2024-02-28 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0024_rename_stripe_id_order_sid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdeliveryaddress',
            name='customer',
        ),
        migrations.AddField(
            model_name='orderdeliveryaddress',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
