# Generated by Django 4.1.13 on 2024-02-28 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_remove_orderdeliveryaddress_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdeliveryaddress',
            old_name='street_address',
            new_name='street',
        ),
    ]
