# Generated by Django 4.1.13 on 2024-02-28 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_rename_order_id_order_oid_remove_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='catname',
            new_name='name',
        ),
    ]
