# Generated by Django 4.1.13 on 2024-02-28 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0028_rename_catname_collection_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='product_sku',
            new_name='sku',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='shop.product'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
