# Generated by Django 4.1.13 on 2024-02-28 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_rename_document_basket_oid_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='document',
            new_name='oid',
        ),
    ]
