# Generated by Django 4.1.13 on 2024-02-28 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_rename_document_transaction_oid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='customer_id',
            new_name='sid',
        ),
    ]
