# Generated by Django 4.1.13 on 2024-02-28 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_rename_customer_id_transaction_sid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='quantity',
            new_name='qty',
        ),
    ]
