# Generated by Django 4.1.13 on 2024-02-29 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_order_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdeliveryaddress',
            name='sid',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
