# Generated by Django 4.1.13 on 2024-02-29 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_orderdeliveryaddress_sid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdeliveryaddress',
            name='sid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.stripecustomer'),
        ),
    ]
