# Generated by Django 4.1.13 on 2024-02-29 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_alter_orderdeliveryaddress_sid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdeliveryaddress',
            name='sid',
            field=models.CharField(default='', max_length=255),
        ),
    ]
